export LIVEKIT_URL=YOUR_LIVEKIT_URL
export LIVEKIT_API_KEY=YOUR_LIVEKIT_API_KEY
export LIVEKIT_API_SECRET=YOUR_LIVEKIT_API_SECRET
export DEEPGRAM_API_KEY=YOUR_DEEPGRAM_API_KEY
export OPENAI_API_KEY=YOUR_OPENAI_API_KEY
export QDRANT_URL = YOUR_QDRANT_URL
export QDRANT_API_KEY = YOUR_QDRANT_API_KEY 
export X-Shopify-Access-Token = YOUR_X-Shopify-Access-Token